version: "3.1"
services:

    'filestorage':
      build: ./
      container_name: filestorage-api
      working_dir: /usr/src/app
      volumes:
        - ./:/usr/src/app
      ports:
        - "80:80"
