version: "3.1"
services:

    'filestorage':
      build: ./
      container_name: filestorage-api
      working_dir: /srv/filestorage_api
      volumes:
        - ./:/srv/filestorage_api
      ports:
        - "80:80"
